# Generated by Django 5.2.15 on 2026-06-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotRouterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_check_at', models.DateTimeField(auto_now=True)),
                ('status_message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('corporate_email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=140)),
                ('estimated_annual_budget', models.CharField(choices=[('UNDER_10K', 'Under $10k'), ('10K_TO_50K', '$10k-$50k'), ('ABOVE_50K', 'Greater than $50k')], max_length=20)),
                ('estimated_budget_value', models.PositiveIntegerField(default=0)),
                ('local_status', models.CharField(choices=[('INGESTED', 'Ingested'), ('REJECTED', 'Rejected')], default='INGESTED', max_length=20)),
                ('hubspot_sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('PAUSED', 'Paused'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('hubspot_contact_id', models.CharField(blank=True, max_length=50)),
                ('hubspot_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
